# Generated by Django 3.2.3 on 2021-08-11 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Trio', 'Trio'), ('Quatro', 'Quatro'), ('etc', 'etc')], default='Solo', max_length=100)),
                ('category', models.CharField(choices=[('Boy Group', 'Boy Group'), ('Girl Group', 'Girl Group'), ('Rock Band', 'Rock Band'), ('Hip-Hop', 'Hip-Hop'), ('Etc', 'Etc')], default='Boy Group', max_length=100)),
                ('like_users', models.ManyToManyField(related_name='like_artists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
