# Generated by Django 3.2.3 on 2021-08-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210811_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='group',
        ),
        migrations.AddField(
            model_name='artist',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
