# Generated by Django 3.2.3 on 2021-08-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210811_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='category',
            field=models.CharField(choices=[('남자 아이돌', '남자 아이돌'), ('여자 아이돌', '여자 아이돌'), ('힙합', '랩/힙합'), ('인디음악', '인디음악'), ('발라드', '발라드'), ('락밴드', '락밴드')], default='Boy Group', max_length=100),
        ),
    ]
