# Generated by Django 3.2.3 on 2021-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_artist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_back',
            field=models.ImageField(blank=True, upload_to='post/'),
        ),
    ]
