# Generated by Django 3.2.3 on 2021-08-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_artist_image_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_back_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
